import 'package:diu_cpc/models/event_model.dart';

class DemoEventData {
  static List<EventModel> upcoming() {
    final now = DateTime.now();
    return [
      EventModel(
        id: 'demo1',
        title: 'Flutter Workshop: Build your first App',
        description: 'Hands-on workshop covering Flutter basics and best practices. Perfect for beginners.',
        agenda: '10:00 AM - Intro to Flutter\n10:30 AM - Widgets 101\n11:30 AM - State Management intro\n12:30 PM - Q&A',
        startDateTime: now.add(const Duration(days: 2, hours: 3)),
        endDateTime: now.add(const Duration(days: 2, hours: 6)),
        venue: 'DIU Auditorium, Daffodil Smart City',
        location: '23.876097,90.320289',
        category: EventCategory.workshop,
        status: EventStatus.upcoming,
        organizerName: 'DIU CPC',
        organizerEmail: 'cpc@daffodilvarsity.edu.bd',
        speakers: const ['John Doe (Google Developer Expert)', 'Jane Smith (Flutter Dev)'],
        maxParticipants: 100,
        currentParticipants: 65,
        registeredUsers: const [],
        waitlistUsers: const [],
        imageUrl: 'https://images.unsplash.com/photo-1556761175-4b46a572b786?q=80&w=1600&auto=format&fit=crop',
        requirements: const ['Bring your laptop', 'Install Flutter SDK beforehand'],
        requiresApproval: false,
        registrationFee: 0,
        registrationDeadline: now.add(const Duration(days: 1, hours: 20)),
        createdAt: now,
        updatedAt: now,
        createdBy: 'demo',
        additionalInfo: {
          'mediaUrls': [
            'https://images.unsplash.com/photo-1551836022-d5d88e9218df?q=80&w=1600&auto=format&fit=crop',
            'https://images.unsplash.com/photo-1543269865-cbf427effbad?q=80&w=1600&auto=format&fit=crop'
          ],
          'approvalStatus': 'approved',
        },
      ),
      EventModel(
        id: 'demo2',
        title: 'Programming Contest - Fall Challenge',
        description: 'Sharpen your problem-solving skills in our intra-university programming contest.',
        agenda: '09:30 AM - Check-in\n10:00 AM - Contest starts\n01:00 PM - Contest ends\n01:30 PM - Prize giving',
        startDateTime: now.add(const Duration(days: 7, hours: 1)),
        endDateTime: now.add(const Duration(days: 7, hours: 5)),
        venue: 'Lab 301, Department of CSE',
        location: 'Daffodil Smart City',
        category: EventCategory.contest,
        status: EventStatus.upcoming,
        organizerName: 'DIU CPC',
        organizerEmail: 'cpc@diu.edu.bd',
        speakers: const ['Problem Setters Team'],
        maxParticipants: 80,
        currentParticipants: 80,
        registeredUsers: const [],
        waitlistUsers: const [],
        imageUrl: 'https://images.unsplash.com/photo-1529336953121-ad5a0d43d0f7?q=80&w=1600&auto=format&fit=crop',
        requirements: const ['Competitive programming account (Codeforces/HackerRank)'],
        requiresApproval: false,
        registrationFee: 0,
        registrationDeadline: now.add(const Duration(days: 6, hours: 20)),
        createdAt: now,
        updatedAt: now,
        createdBy: 'demo',
        additionalInfo: {
          'approvalStatus': 'approved',
        },
      ),
      EventModel(
        id: 'demo3',
        title: 'Career Talk: Cracking Tech Interviews',
        description: 'Learn strategies for coding interviews, system design, and resume tips.',
        agenda: '02:00 PM - Resume Walkthrough\n03:00 PM - DSA Strategies\n04:00 PM - Mock Q&A',
        startDateTime: now.add(const Duration(days: 12, hours: 2)),
        endDateTime: now.add(const Duration(days: 12, hours: 5)),
        venue: 'Seminar Hall 2',
        location: 'Daffodil Smart City',
        category: EventCategory.seminar,
        status: EventStatus.upcoming,
        organizerName: 'DIU CPC',
        organizerEmail: 'cpc@diu.edu.bd',
        speakers: const ['HR Panel', 'Senior Engineers Panel'],
        maxParticipants: 150,
        currentParticipants: 120,
        registeredUsers: const [],
        waitlistUsers: const [],
        imageUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?q=80&w=1600&auto=format&fit=crop',
        requirements: const ['Bring notebook'],
        requiresApproval: false,
        registrationFee: 0,
        registrationDeadline: now.add(const Duration(days: 11, hours: 18)),
        createdAt: now,
        updatedAt: now,
        createdBy: 'demo',
        additionalInfo: {
          'approvalStatus': 'approved',
          'mediaUrls': [
            'https://images.unsplash.com/photo-1491947153227-33d59da6c448?q=80&w=1600&auto=format&fit=crop'
          ],
        },
      ),
    ];
  }

  static List<EventModel> past() {
    final now = DateTime.now();
    return [
      EventModel(
        id: 'demo_p1',
        title: 'Tech Seminar: AI Trends 2025',
        description: 'Exploring the latest trends in AI and ML with industry experts.',
        agenda: 'Keynote + Panel Discussion',
        startDateTime: now.subtract(const Duration(days: 14, hours: 2)),
        endDateTime: now.subtract(const Duration(days: 14)),
        venue: 'Main Auditorium',
        location: 'Daffodil Smart City',
        category: EventCategory.seminar,
        status: EventStatus.completed,
        organizerName: 'DIU CPC',
        organizerEmail: 'cpc@diu.edu.bd',
        speakers: const ['Prof. A. Rahman', 'Dr. B. Karim'],
        maxParticipants: 200,
        currentParticipants: 180,
        registeredUsers: const [],
        waitlistUsers: const [],
        imageUrl: 'https://images.unsplash.com/photo-1503424886305-4ca6c92387be?q=80&w=1600&auto=format&fit=crop',
        requirements: const [],
        requiresApproval: false,
        registrationFee: 0,
        registrationDeadline: null,
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 14)),
        createdBy: 'demo',
        additionalInfo: {
          'mediaUrls': [
            'https://images.unsplash.com/photo-1551836022-d5d88e9218df?q=80&w=1600&auto=format&fit=crop',
            'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=1600&auto=format&fit=crop',
            'https://images.unsplash.com/photo-1529336953121-ad5a0d43d0f7?q=80&w=1600&auto=format&fit=crop'
          ],
          'approvalStatus': 'approved',
        },
      ),
      EventModel(
        id: 'demo_p2',
        title: 'Web Dev Bootcamp Recap',
        description: 'Hands-on bootcamp covering HTML, CSS, JS basics with a final project.',
        agenda: 'Project presentations',
        startDateTime: now.subtract(const Duration(days: 30, hours: 4)),
        endDateTime: now.subtract(const Duration(days: 30, hours: 1)),
        venue: 'Lab 105',
        location: 'Daffodil Smart City',
        category: EventCategory.workshop,
        status: EventStatus.completed,
        organizerName: 'DIU CPC',
        organizerEmail: 'cpc@diu.edu.bd',
        speakers: const ['Mentor Team'],
        maxParticipants: 60,
        currentParticipants: 58,
        registeredUsers: const [],
        waitlistUsers: const [],
        imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1600&auto=format&fit=crop',
        requirements: const [],
        requiresApproval: false,
        registrationFee: 0,
        registrationDeadline: null,
        createdAt: now.subtract(const Duration(days: 40)),
        updatedAt: now.subtract(const Duration(days: 30)),
        createdBy: 'demo',
        additionalInfo: {
          'mediaUrls': [
            'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=1600&auto=format&fit=crop'
          ],
          'approvalStatus': 'approved',
        },
      ),
      EventModel(
        id: 'demo_p3',
        title: 'Hackathon 24-Hour Sprint',
        description: 'Teams built prototypes overnight. Winners announced at closing ceremony.',
        agenda: 'Closing and awards',
        startDateTime: now.subtract(const Duration(days: 45, hours: 10)),
        endDateTime: now.subtract(const Duration(days: 45, hours: 6)),
        venue: 'Innovation Lab',
        location: 'Daffodil Smart City',
        category: EventCategory.contest,
        status: EventStatus.completed,
        organizerName: 'DIU CPC',
        organizerEmail: 'cpc@diu.edu.bd',
        speakers: const ['Judges Panel'],
        maxParticipants: 100,
        currentParticipants: 95,
        registeredUsers: const [],
        waitlistUsers: const [],
        imageUrl: 'https://images.unsplash.com/photo-1551836022-4c4c79ecde51?q=80&w=1600&auto=format&fit=crop',
        requirements: const [],
        requiresApproval: false,
        registrationFee: 0,
        registrationDeadline: null,
        createdAt: now.subtract(const Duration(days: 55)),
        updatedAt: now.subtract(const Duration(days: 45)),
        createdBy: 'demo',
        additionalInfo: {
          'mediaUrls': [
            'https://images.unsplash.com/photo-1543269865-cbf427effbad?q=80&w=1600&auto=format&fit=crop'
          ],
          'approvalStatus': 'approved',
        },
      ),
    ];
  }
}
