// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOuKYZx6DZNLi0qF4wAxdZwOdDM5XoRhA',
    appId: '1:741543342347:web:f1132b019f52a83de0720e',
    messagingSenderId: '741543342347',
    projectId: 'fir-tutorial-af5d5',
    authDomain: 'fir-tutorial-af5d5.firebaseapp.com',
    storageBucket: 'fir-tutorial-af5d5.firebasestorage.app',
    measurementId: 'G-ETJSQVNSWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASA46LiErYpVViFJL5MhwD-TjzXDRwKQI',
    appId: '1:741543342347:android:f1bc06528566b907e0720e',
    messagingSenderId: '741543342347',
    projectId: 'fir-tutorial-af5d5',
    storageBucket: 'fir-tutorial-af5d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNWwH3jf0oR9VH5myvJI2fm_lzfHJtkGI',
    appId: '1:741543342347:ios:a0d544063d32ce0ce0720e',
    messagingSenderId: '741543342347',
    projectId: 'fir-tutorial-af5d5',
    storageBucket: 'fir-tutorial-af5d5.firebasestorage.app',
    iosBundleId: 'com.example.diuCpc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNWwH3jf0oR9VH5myvJI2fm_lzfHJtkGI',
    appId: '1:741543342347:ios:a0d544063d32ce0ce0720e',
    messagingSenderId: '741543342347',
    projectId: 'fir-tutorial-af5d5',
    storageBucket: 'fir-tutorial-af5d5.firebasestorage.app',
    iosBundleId: 'com.example.diuCpc',
  );
}
